### ISSUE TITLE
DNS does not resolve

### ISSUE THREAD

**Issue by antp** [nerves-project/nerves_networking#15] opened 2016-08-05 17:22 UTC
I have configured networking with a static IP.
I have set the DNS entry for networking to Googles, 8.8.8.8 and 8.8.4.4. public servers

Using HTTPoison if I do a get with a domain name I get a :nxdomain error. IP address is fine.

Using :inet_res.lookup('nerves-project.org', :in, :a, [nameservers: [{{8,8,8,8}, 53}]]) resolves fine

Any pointers to what I may have misconfigured?

**Comment by bendiken** [comment] 2016-08-05 17:53
I also ran into what's probably the very same problem when developing https://github.com/nerves-project/nerves_system_qemu_arm/pull/2

It's easy to reproduce, harder to work around:

    iex(1)> :inet_res.lookup('nerves-project.org', :in, :a)
    []
    iex(2)> :inet_res.lookup('nerves-project.org', :in, :a, [nameservers: [{{8,8,8,8}, 53}]])
    [{192, 30, 252, 153}, {192, 30, 252, 154}]

Both expressions should return the same result (the latter one) if networking has been configured to use 8.8.8.8 and 8.8.4.4 (or any other sane DNS, really).

**Comment by bendiken** [comment] 2016-08-08 00:12
Also reproduced this prob with the `hello_network` example on the `rpi` hardware target.

**Comment by antp** [comment] 2016-08-08 14:40
After looking at the Erlang source to find when the ERL_INETRC environment variable was read.

I found that even though the :inets application was listed in the mix config and inet_db had been started it had not configured itself. I assume! that is because :inets is started before the network is configured.

To fix the DNS issue I added :inet_config.init after the network is configured.

Any advice on is this the correct fix?

**Comment by bendiken** [comment] 2016-08-08 14:59
Good investigating, @antp. Pinging @ghitchens and @fhunleth...

**Comment by fhunleth** [comment] 2016-08-08 17:27
@antp, @bendiken: It sounds like `inet_res` is caching the `/etc/resolv.conf` file rather than reloading it (or not caching it) like the C library does. I guess that `:inet_config.init` needs to be called every time `/etc/resolv.conf` is modified. Or, it could be that the inets code doesn't follow symlinks when watching `/etc/resolv.conf`, since it gets symlinked to `/tmp` on Nerves.

**Comment by fhunleth** [comment] 2016-08-10 13:45
@antp, @bendiken: @mobileoverlord just ran into this issue as well and found that updating `/etc/erl_inetrc` fixed it for him. You can see his commit at: https://github.com/nerves-project/nerves_system_br/commit/5d589ef0f3d3ab7fc9881e3fc581c0cf9e71c66b. Could you see if adding his new version of `erl_inetrc` to your project-specific rootfs-additions directory fixes this for you?

**Comment by antp** [comment] 2016-08-10 14:42
I can confirm, for me this fixes the DNS issue.

**Comment by fhunleth** [comment] 2016-08-10 15:33
I'm going to close this issue, but please reopen if `erl_inetrc` turns out to not be a complete fix. 

The `/etc/erl_inetrc` change will hopefully be officially released in the next day or two. Then you'll get it without overriding it manually in your rootfs-additions once you upgrade your Nerves system image. 

Thanks again for reporting this and confirming the fix.

**Closed by fhunleth** 2016-08-10 15:33 UTC

**Comment by bendiken** [comment] 2016-08-11 06:06
Just to add a link to the relevant pull request: https://github.com/nerves-project/nerves_system_br/pull/77
